server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 598540845327-n797nuk32okinfq6av6ncpmm6jtvj5ou.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: dnflgkdiscjstk98@

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/junil/web-3-202210/library/library/upload/

